"use client";
import { Canvas, useThree } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useEffect, useRef, useState } from "react";
import type { FloorPlanDocument } from "@/lib/floorplan/document";

type Product={id:string;sku:string;name:string;width_mm:number|null;depth_mm:number|null;height_mm:number|null;material_code:string|null};
type Placement={id:string;product:Product;x:number;z:number;color:string};
type Scene="AXONOMETRIC"|"PLAN"|"LIVING"|"MASTER";

function Wall({wall,openings,color}:{wall:FloorPlanDocument["walls"][number];openings:NonNullable<FloorPlanDocument["openings"]>;color:string}){
 const dx=(wall.end.xMm-wall.start.xMm)/1000,dz=(wall.end.yMm-wall.start.yMm)/1000,length=Math.hypot(dx,dz),angle=-Math.atan2(dz,dx),height=wall.heightMm/1000;
 const cuts=openings.filter(o=>o.wallId===wall.objectId).sort((a,b)=>a.offsetMm-b.offsetMm); const parts:Array<{from:number;to:number;y:number;h:number}>=[]; let cursor=0;
 for(const cut of cuts){const from=Math.max(0,cut.offsetMm/1000),to=Math.min(length,(cut.offsetMm+cut.widthMm)/1000);if(from>cursor)parts.push({from:cursor,to,y:height/2,h:height});const sill=cut.sillHeightMm/1000,top=(cut.sillHeightMm+cut.heightMm)/1000;if(sill>0)parts.push({from,to,y:sill/2,h:sill});if(top<height)parts.push({from,to,y:(top+height)/2,h:height-top});cursor=Math.max(cursor,to)} if(cursor<length)parts.push({from:cursor,to:length,y:height/2,h:height});
 return <>{parts.map((part,i)=>{const mid=(part.from+part.to)/2,ratio=length?mid/length:0,x=wall.start.xMm/1000+dx*ratio,z=wall.start.yMm/1000+dz*ratio;return <mesh key={i} position={[x,part.y,z]} rotation={[0,angle,0]} castShadow receiveShadow><boxGeometry args={[part.to-part.from,part.h,wall.thicknessMm/1000]}/><meshStandardMaterial color={color}/></mesh>})}</>;
}
function CameraRig({scene}:{scene:Scene}){const {camera}=useThree();useEffect(()=>{const p=scene==="PLAN"?[3.2,12,3.5]:scene==="LIVING"?[1.2,1.7,1.2]:scene==="MASTER"?[5.2,1.7,1.2]:[8,10,10];camera.position.set(...(p as [number,number,number]));camera.lookAt(3.2,0,3.5);camera.updateProjectionMatrix()},[camera,scene]);return null}
export function SpaceSceneCanvas({document,products=[]}:{document:FloorPlanDocument;products?:Product[]}){
 const [placements,setPlacements]=useState<Placement[]>([]),[scene,setScene]=useState<Scene>("AXONOMETRIC"),[wallColor,setWallColor]=useState("#e9e5dc"),[floorColor,setFloorColor]=useState("#d7c9b4");const capture=useRef<HTMLCanvasElement|null>(null);
 function drop(e:React.DragEvent<HTMLDivElement>){e.preventDefault();const product=products.find(p=>p.id===e.dataTransfer.getData("product/id"));if(!product)return;const r=e.currentTarget.getBoundingClientRect(),x=Math.max(.2,Math.min(6.2,(e.clientX-r.left)/r.width*6.4)),z=Math.max(.2,Math.min(6.8,(e.clientY-r.top)/r.height*7));setPlacements(v=>[...v,{id:crypto.randomUUID(),product,x,z,color:"#b98763"}])}
 function exportPng(){if(!capture.current)return;const a=documentGlobal.createElement("a");a.href=capture.current.toDataURL("image/png");a.download=`scene-${scene.toLowerCase()}.png`;a.click()}
 const documentGlobal=globalThis.document;
 return <div className="grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)_220px]"><aside className="rounded-xl border bg-white p-3"><h3 className="text-sm font-bold">商品库</h3><div className="mt-3 space-y-2">{products.length?products.map(p=><div key={p.id} draggable onDragStart={e=>e.dataTransfer.setData("product/id",p.id)} className="cursor-grab rounded-lg border p-2 text-xs"><b>{p.name}</b><div>{p.sku}</div></div>):<p className="text-xs text-slate-400">先在采购模块建立SKU</p>}</div></aside><div onDragOver={e=>e.preventDefault()} onDrop={drop} className="h-[560px] overflow-hidden rounded-xl border bg-stone-100"><Canvas gl={{preserveDrawingBuffer:true}} onCreated={({gl})=>{capture.current=gl.domElement}} shadows orthographic camera={{position:[8,10,10],zoom:65,near:.1,far:100}}><CameraRig scene={scene}/><color attach="background" args={["#f3f1ec"]}/><ambientLight intensity={1.6}/><directionalLight position={[6,10,4]} intensity={2} castShadow/><mesh position={[3.2,-.03,3.5]} receiveShadow><boxGeometry args={[6.4,.06,7]}/><meshStandardMaterial color={floorColor}/></mesh>{document.walls.map(w=><Wall key={w.objectId} wall={w} openings={document.openings??[]} color={w.wallType==="EXTERIOR"?"#d6d3cc":wallColor}/>)}{placements.map(p=><mesh key={p.id} position={[p.x,(p.product.height_mm??800)/2000,p.z]} castShadow><boxGeometry args={[(p.product.width_mm??800)/1000,(p.product.height_mm??800)/1000,(p.product.depth_mm??600)/1000]}/><meshStandardMaterial color={p.color}/></mesh>)}<gridHelper args={[14,28,"#9aa7a1","#d7d9d5"]}/><OrbitControls makeDefault target={[3.2,0,3.5]}/></Canvas></div><aside className="rounded-xl border bg-white p-3 text-xs"><h3 className="text-sm font-bold">场景与材质</h3><div className="mt-3 grid grid-cols-2 gap-2">{(["AXONOMETRIC","PLAN","LIVING","MASTER"] as Scene[]).map(s=><button key={s} onClick={()=>setScene(s)} className={`rounded border p-2 ${scene===s?"bg-teal-800 text-white":""}`}>{s}</button>)}</div><label className="mt-4 block">墙面颜色<input type="color" value={wallColor} onChange={e=>setWallColor(e.target.value)} className="ml-2"/></label><label className="mt-3 block">地面颜色<input type="color" value={floorColor} onChange={e=>setFloorColor(e.target.value)} className="ml-2"/></label><p className="mt-4 text-slate-500">拖动左侧商品到画布；门窗开口由户型opening几何切割。</p><button onClick={exportPng} className="mt-4 w-full rounded bg-teal-800 p-2 text-white">导出当前场景PNG</button></aside></div>;
}
