import { z } from "zod";
import { requireOwnedProject, accessErrorResponse } from "@/lib/auth/project-access";
import { createQuote, getLatestQuote, listBom, listProducts, replaceBom, upsertProduct } from "@/lib/commerce/repository";

const Product=z.object({sku:z.string().min(1),name:z.string().min(1),category:z.string().min(1),widthMm:z.number().positive().nullable().optional(),depthMm:z.number().positive().nullable().optional(),heightMm:z.number().positive().nullable().optional(),materialCode:z.string().nullable().optional(),supplier:z.string().nullable().optional(),unit:z.string().min(1).optional(),unitCost:z.number().nonnegative(),unitPrice:z.number().nonnegative(),dimensionsVerified:z.boolean().optional(),sourceAssetId:z.string().nullable().optional()});
const Bom=z.object({sku:z.string().min(1),name:z.string().min(1),quantity:z.number().positive(),unit:z.string().min(1),unitCost:z.number().nonnegative(),unitPrice:z.number().nonnegative(),materialCode:z.string().nullable().optional(),roomCode:z.string().nullable().optional(),productId:z.string().nullable().optional()});

export async function GET(_request:Request,context:{params:Promise<{id:string}>}){ const {id}=await context.params; try{await requireOwnedProject(id);return Response.json({products:listProducts(id),bom:listBom(id),quote:getLatestQuote(id)});}catch(e){return accessErrorResponse(e)??Response.json({error:"INTERNAL_ERROR"},{status:500});}}
export async function PUT(request:Request,context:{params:Promise<{id:string}>}){const {id}=await context.params;try{await requireOwnedProject(id);const body=await request.json();if(body.product){const value=Product.parse(body.product);return Response.json({product:upsertProduct(id,value)});}if(body.bom){const items=z.array(Bom).parse(body.bom);const sourceVersion=z.string().min(1).parse(body.sourceVersion);const bom=replaceBom(id,sourceVersion,items);return Response.json({bom});}if(body.quote){const value=z.object({version:z.string().min(1),currency:z.literal("HKD").default("HKD"),designFee:z.number().nonnegative().optional(),discount:z.number().nonnegative().optional(),tax:z.number().nonnegative().optional()}).parse(body.quote);return Response.json({quote:createQuote(id,value)});}return Response.json({error:"INVALID_COMMERCE_OPERATION"},{status:400});}catch(e){const access=accessErrorResponse(e);if(access)return access;return Response.json({error:e instanceof Error?e.message:"INVALID_INPUT"},{status:400});}}
